export const medicalCouncils = [
  { name: 'Andhra Pradesh Medical Council' },
  { name: 'Arunachal Pradesh Medical Council' },
  { name: 'Assam Medical Council' },
  { name: 'Bihar Medical Council' },
  { name: 'Chattisgarh Medical Council' },
  { name: 'Delhi Medical Council' },
  { name: 'Goa Medical Council' },
  { name: 'Gujarat Medical Council' },
  { name: 'Haryana State Dental & Medical Council' },
  { name: 'Himachal Pradesh Medical Council' },
  { name: 'Jammu & Kashmir Medical Council' },
  { name: 'Jharkhand Medical Council' },
  { name: 'Karnataka Medical Council' },
  { name: 'Kerala Medical Council' },
  { name: 'Madhya Pradesh Medical Council' },
  { name: 'Maharashtra Medical Council' },
  { name: 'Manipur Medical Council' },
  { name: 'Meghalaya Medical Council' },
  { name: 'Mizoram Medical Council' },
  { name: 'Nagaland Medical Council' },
  { name: 'Orissa Medical Council' },
  { name: 'Punjab Medical Council' },
  { name: 'Rajasthan Medical Council' },
  { name: 'Sikkim Medical Council' },
  { name: 'Tamil Nadu Medical Council' },
  { name: 'Telangana Medical Council' },
  { name: 'Tripura Medical Council' },
  { name: 'Uttarakhand Medical Council' },
  { name: 'Uttar Pradesh Medical Council' },
  { name: 'West Bengal Medical Council' },
];
